services:
  - type: web
    name: reinvent4-app
    env: docker
    repo: https://github.com/bhatnira/REINVENT4-APP.git
    region: oregon # Choose your preferred region
    plan: starter # Can be upgraded to standard or pro
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHONUNBUFFERED
        value: 1
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false
    healthCheckPath: /_stcore/health
    numInstances: 1
    disk:
      name: reinvent4-disk
      mountPath: /app/data
      sizeGB: 20
    # Optional: Add custom domains
    # domains:
    #   - reinvent4.yourdomain.com
